### ISSUE TITLE
don't include lib in tests directories

### ISSUE THREAD

**Issue by TheSnakeWitcher** [llllvvuu/neotest-foundry#3]
Hi mate, I was playing around and I found that `Neotest summary` show not only the `test` dir, it show `lib` dir too. I think that usually the test from the used libs shouldn't  be executed, that code shold be tested in their respectives projects. What do you think ?  I know that these can be configured but i mean as default behavior

**Comment by llllvvuu** [comment]
Sure, updated the default behavior.
